[package]
name = "day24"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
filelib = { path = "../filelib" }
gridlib = { path = "../gridlib" }
rustc-hash = { "version" = "1.1.0" }